import { Button } from "@/shared/ui/Button";
import { comfortaa } from "@/shared/fonts/comfortaa";
import Head from "next/head";
import { classNames } from "@/shared/lib/classNames/classNames";
import { getStack } from "@/shared/ui/Stack";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                {/* <meta
                    name="description"
                    content="Generated by create next app"
                /> */}
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <main className={comfortaa.className}>
                <div
                    className={classNames("", {}, [
                        getStack({
                            direction: "column",
                            justify: "center",
                            align: "center",
                            gap: "32",
                            fullHeight: true,
                        }),
                    ])}
                >
                    <div>123</div>
                    <Button>Кнопка</Button>
                </div>
            </main>
        </>
    );
}
